"""add is_debt to sales

Revision ID: 0ddb94118ce7
Revises: a8a67761d947
Create Date: 2026-01-11 21:34:44.478659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddb94118ce7'
down_revision: Union[str, Sequence[str], None] = 'a8a67761d947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку, но разрешаем NULL (временно)
    op.add_column('sales', sa.Column('is_debt', sa.Boolean(), nullable=True))
    
    # 2. Заполняем все старые записи значением False (Долга нет)
    op.execute("UPDATE sales SET is_debt = false")
    
    # 3. Делаем колонку обязательной (NOT NULL)
    op.alter_column('sales', 'is_debt', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'is_debt')
    # ### end Alembic commands ###
