"""add client is_active

Revision ID: 46e5b6dc9f92
Revises: f2b3ee87e00c
Create Date: 2025-12-30 02:24:33.276101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e5b6dc9f92'
down_revision: Union[str, Sequence[str], None] = 'f2b3ee87e00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку как nullable=True (можно пустым)
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # 2. Заполняем всех существующих клиентов значением True (Активен)
    op.execute("UPDATE clients SET is_active = true")
    
    # 3. Делаем колонку обязательной (nullable=False)
    op.alter_column('clients', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
