"""Refactor logic

Revision ID: 9b9ac17c2b1d
Revises: 46e5b6dc9f92
Create Date: 2026-01-09 22:00:30.426009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9ac17c2b1d'
down_revision: Union[str, Sequence[str], None] = '46e5b6dc9f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('products', sa.Column('items_per_pack', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('products', 'sell_price', new_column_name='recommended_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.alter_column('products', 'recommended_price', new_column_name='sell_price')
    op.drop_column('products', 'items_per_pack')
    # ### end Alembic commands ###
